export const INIT_PAYMENTS = "INIT_PAYMENTS";

export const INIT_PAYMENTS_SUCCESS = "INIT_PAYMENTS_SUCCESS";

export const ADD_PAYMENT = "ADD_PAYMENT";

export const ADD_PAYMENT_SUCCESS = "ADD_PAYMENT_SUCCESS";
