export const INIT_CLIENTS = 'INIT_CLIENTS';

export const INIT_CLIENTS_SUCCESS = 'INIT_CLIENTS_SUCCESS';

export const ADD_CLIENT = 'ADD_CLIENT';

export const ADD_CLIENT_SUCCESS = 'ADD_CLIENT_SUCCESS';

export const UPDATE_CLIENT = 'UPDATE_CLIENT';

export const UPDATE_CLIENT_SUCCESS = 'UPDATE_CLIENT_SUCCESS';
