export const INIT_MENTORS = "INIT_MENTORS";

export const INIT_MENTORS_SUCCESS = "INIT_MENTORS_SUCCESS";

export const ADD_MENTOR = "ADD_MENTOR";

export const ADD_MENTOR_SUCCESS = "ADD_MENTOR_SUCCESS";
